// AUTO-GENERATED by scripts/gen-bank-logos.js — do not edit by hand.
// Source: assets/bank-logos/*.svg  (80 logos)
import type { FC } from 'react';
import type { SvgProps } from 'react-native-svg';

import L0 from '../../assets/bank-logos/Bank Name=ABN AMRO.svg';
import L1 from '../../assets/bank-logos/Bank Name=AU Small Finance Bank.svg';
import L2 from '../../assets/bank-logos/Bank Name=Abu Dhabi Commercial Bank.svg';
import L3 from '../../assets/bank-logos/Bank Name=Airtel Payments Bank.svg';
import L4 from '../../assets/bank-logos/Bank Name=American Express.svg';
import L5 from '../../assets/bank-logos/Bank Name=Australia and New Zealand Banking Group.svg';
import L6 from '../../assets/bank-logos/Bank Name=Axis bank.svg';
import L7 from '../../assets/bank-logos/Bank Name=BNP Paribas.svg';
import L8 from '../../assets/bank-logos/Bank Name=Bandhan Bank.svg';
import L9 from '../../assets/bank-logos/Bank Name=Bank Maybank Indonesia.svg';
import L10 from '../../assets/bank-logos/Bank Name=Bank of America.svg';
import L11 from '../../assets/bank-logos/Bank Name=Bank of Bahrain and Kuwait.svg';
import L12 from '../../assets/bank-logos/Bank Name=Bank of Baroda.svg';
import L13 from '../../assets/bank-logos/Bank Name=Bank of Ceylon.svg';
import L14 from '../../assets/bank-logos/Bank Name=Bank of China.svg';
import L15 from '../../assets/bank-logos/Bank Name=Bank of India.svg';
import L16 from '../../assets/bank-logos/Bank Name=Bank of Maharastra.svg';
import L17 from '../../assets/bank-logos/Bank Name=Barclays Bank.svg';
import L18 from '../../assets/bank-logos/Bank Name=CSB Bank.svg';
import L19 from '../../assets/bank-logos/Bank Name=Canara Bank.svg';
import L20 from '../../assets/bank-logos/Bank Name=Central Bank of India.svg';
import L21 from '../../assets/bank-logos/Bank Name=Citi Bank.svg';
import L22 from '../../assets/bank-logos/Bank Name=City Union Bank.svg';
import L23 from '../../assets/bank-logos/Bank Name=Credit Suisse.svg';
import L24 from '../../assets/bank-logos/Bank Name=Crédit Agricole Corporate and Investment Bank.svg';
import L25 from '../../assets/bank-logos/Bank Name=DBS Bank.svg';
import L26 from '../../assets/bank-logos/Bank Name=DCB Bank.svg';
import L27 from '../../assets/bank-logos/Bank Name=Deutsche Bank.svg';
import L28 from '../../assets/bank-logos/Bank Name=Dhanlaxmi Bank.svg';
import L29 from '../../assets/bank-logos/Bank Name=Doha Bank.svg';
import L30 from '../../assets/bank-logos/Bank Name=ESAF Small Finance Bank Ltd.svg';
import L31 from '../../assets/bank-logos/Bank Name=Emirates NBD.svg';
import L32 from '../../assets/bank-logos/Bank Name=FINO Payments Bank.svg';
import L33 from '../../assets/bank-logos/Bank Name=First Abu Dhabi Bank.svg';
import L34 from '../../assets/bank-logos/Bank Name=FirstRand Bank.svg';
import L35 from '../../assets/bank-logos/Bank Name=HDFC Bank.svg';
import L36 from '../../assets/bank-logos/Bank Name=HSBC Bank.svg';
import L37 from '../../assets/bank-logos/Bank Name=ICICI Bank.svg';
import L38 from '../../assets/bank-logos/Bank Name=IDBI Bank.svg';
import L39 from '../../assets/bank-logos/Bank Name=IDFC Bank.svg';
import L40 from '../../assets/bank-logos/Bank Name=India Post Payments Bank.svg';
import L41 from '../../assets/bank-logos/Bank Name=Indian Bank.svg';
import L42 from '../../assets/bank-logos/Bank Name=Indian Overseas Bank.svg';
import L43 from '../../assets/bank-logos/Bank Name=Induslnd Bank.svg';
import L44 from '../../assets/bank-logos/Bank Name=Industrial & Commercial Bank of China.svg';
import L45 from '../../assets/bank-logos/Bank Name=Industrial Bank of Korea.svg';
import L46 from '../../assets/bank-logos/Bank Name=JPMorgan Chase.svg';
import L47 from '../../assets/bank-logos/Bank Name=Jammu & Kashmir Bank.svg';
import L48 from '../../assets/bank-logos/Bank Name=Jio Payments Bank.svg';
import L49 from '../../assets/bank-logos/Bank Name=KEB Hana Bank.svg';
import L50 from '../../assets/bank-logos/Bank Name=Karnataka Bank.svg';
import L51 from '../../assets/bank-logos/Bank Name=Kookmin Bank.svg';
import L52 from '../../assets/bank-logos/Bank Name=Kotak Mahindra Bank.svg';
import L53 from '../../assets/bank-logos/Bank Name=Krung Thai Bank.svg';
import L54 from '../../assets/bank-logos/Bank Name=MUFG Bank.svg';
import L55 from '../../assets/bank-logos/Bank Name=Mizuho Corporate Bank.svg';
import L56 from '../../assets/bank-logos/Bank Name=Nainital Bank.svg';
import L57 from '../../assets/bank-logos/Bank Name=NatWest Bank.svg';
import L58 from '../../assets/bank-logos/Bank Name=Paytm Payments Bank.svg';
import L59 from '../../assets/bank-logos/Bank Name=Punjab & Sind Bank.svg';
import L60 from '../../assets/bank-logos/Bank Name=Punjab National Bank.svg';
import L61 from '../../assets/bank-logos/Bank Name=Qatar National Bank.svg';
import L62 from '../../assets/bank-logos/Bank Name=RBL Bank.svg';
import L63 from '../../assets/bank-logos/Bank Name=Sberbank.svg';
import L64 from '../../assets/bank-logos/Bank Name=Scotia Bank.svg';
import L65 from '../../assets/bank-logos/Bank Name=Shinhan Bank.svg';
import L66 from '../../assets/bank-logos/Bank Name=Société Générale.svg';
import L67 from '../../assets/bank-logos/Bank Name=Sonali Bank.svg';
import L68 from '../../assets/bank-logos/Bank Name=South Indian Bank.svg';
import L69 from '../../assets/bank-logos/Bank Name=Standard Chartered Bank.svg';
import L70 from '../../assets/bank-logos/Bank Name=State Bank of India.svg';
import L71 from '../../assets/bank-logos/Bank Name=Sumitomo Mitsui Banking Corporation.svg';
import L72 from '../../assets/bank-logos/Bank Name=Tamilnad Mercantile Bank.svg';
import L73 from '../../assets/bank-logos/Bank Name=UCO Bank.svg';
import L74 from '../../assets/bank-logos/Bank Name=Ujjivan Small Finance Bank.svg';
import L75 from '../../assets/bank-logos/Bank Name=Union Bank.svg';
import L76 from '../../assets/bank-logos/Bank Name=United Overseas Bank.svg';
import L77 from '../../assets/bank-logos/Bank Name=Westpac.svg';
import L78 from '../../assets/bank-logos/Bank Name=Woori Bank.svg';
import L79 from '../../assets/bank-logos/Bank Name=Yes Bank.svg';

/** Normalized bank name → logo component. See BankLogo for the matching rules. */
export const BANK_LOGOS: Record<string, FC<SvgProps>> = {
  'abnamro': L0,
  'ausmallfinancebank': L1,
  'abudhabicommercialbank': L2,
  'airtelpaymentsbank': L3,
  'americanexpress': L4,
  'australiaandnewzealandbankinggroup': L5,
  'axisbank': L6,
  'bnpparibas': L7,
  'bandhanbank': L8,
  'bankmaybankindonesia': L9,
  'bankofamerica': L10,
  'bankofbahrainandkuwait': L11,
  'bankofbaroda': L12,
  'bankofceylon': L13,
  'bankofchina': L14,
  'bankofindia': L15,
  'bankofmaharastra': L16,
  'barclaysbank': L17,
  'csbbank': L18,
  'canarabank': L19,
  'centralbankofindia': L20,
  'citibank': L21,
  'cityunionbank': L22,
  'creditsuisse': L23,
  'creditagricolecorporateandinvestmentbank': L24,
  'dbsbank': L25,
  'dcbbank': L26,
  'deutschebank': L27,
  'dhanlaxmibank': L28,
  'dohabank': L29,
  'esafsmallfinancebankltd': L30,
  'emiratesnbd': L31,
  'finopaymentsbank': L32,
  'firstabudhabibank': L33,
  'firstrandbank': L34,
  'hdfcbank': L35,
  'hsbcbank': L36,
  'icicibank': L37,
  'idbibank': L38,
  'idfcbank': L39,
  'indiapostpaymentsbank': L40,
  'indianbank': L41,
  'indianoverseasbank': L42,
  'induslndbank': L43,
  'industrialandcommercialbankofchina': L44,
  'industrialbankofkorea': L45,
  'jpmorganchase': L46,
  'jammuandkashmirbank': L47,
  'jiopaymentsbank': L48,
  'kebhanabank': L49,
  'karnatakabank': L50,
  'kookminbank': L51,
  'kotakmahindrabank': L52,
  'krungthaibank': L53,
  'mufgbank': L54,
  'mizuhocorporatebank': L55,
  'nainitalbank': L56,
  'natwestbank': L57,
  'paytmpaymentsbank': L58,
  'punjabandsindbank': L59,
  'punjabnationalbank': L60,
  'qatarnationalbank': L61,
  'rblbank': L62,
  'sberbank': L63,
  'scotiabank': L64,
  'shinhanbank': L65,
  'societegenerale': L66,
  'sonalibank': L67,
  'southindianbank': L68,
  'standardcharteredbank': L69,
  'statebankofindia': L70,
  'sumitomomitsuibankingcorporation': L71,
  'tamilnadmercantilebank': L72,
  'ucobank': L73,
  'ujjivansmallfinancebank': L74,
  'unionbank': L75,
  'unitedoverseasbank': L76,
  'westpac': L77,
  'wooribank': L78,
  'yesbank': L79,
};

/** Display names of every bank we have a logo for (sorted) — powers the picker. */
export const BANK_NAMES: string[] = [
  'ABN AMRO',
  'Abu Dhabi Commercial Bank',
  'Airtel Payments Bank',
  'American Express',
  'AU Small Finance Bank',
  'Australia and New Zealand Banking Group',
  'Axis bank',
  'Bandhan Bank',
  'Bank Maybank Indonesia',
  'Bank of America',
  'Bank of Bahrain and Kuwait',
  'Bank of Baroda',
  'Bank of Ceylon',
  'Bank of China',
  'Bank of India',
  'Bank of Maharastra',
  'Barclays Bank',
  'BNP Paribas',
  'Canara Bank',
  'Central Bank of India',
  'Citi Bank',
  'City Union Bank',
  'Crédit Agricole Corporate and Investment Bank',
  'Credit Suisse',
  'CSB Bank',
  'DBS Bank',
  'DCB Bank',
  'Deutsche Bank',
  'Dhanlaxmi Bank',
  'Doha Bank',
  'Emirates NBD',
  'ESAF Small Finance Bank Ltd',
  'FINO Payments Bank',
  'First Abu Dhabi Bank',
  'FirstRand Bank',
  'HDFC Bank',
  'HSBC Bank',
  'ICICI Bank',
  'IDBI Bank',
  'IDFC Bank',
  'India Post Payments Bank',
  'Indian Bank',
  'Indian Overseas Bank',
  'Induslnd Bank',
  'Industrial & Commercial Bank of China',
  'Industrial Bank of Korea',
  'Jammu & Kashmir Bank',
  'Jio Payments Bank',
  'JPMorgan Chase',
  'Karnataka Bank',
  'KEB Hana Bank',
  'Kookmin Bank',
  'Kotak Mahindra Bank',
  'Krung Thai Bank',
  'Mizuho Corporate Bank',
  'MUFG Bank',
  'Nainital Bank',
  'NatWest Bank',
  'Paytm Payments Bank',
  'Punjab & Sind Bank',
  'Punjab National Bank',
  'Qatar National Bank',
  'RBL Bank',
  'Sberbank',
  'Scotia Bank',
  'Shinhan Bank',
  'Société Générale',
  'Sonali Bank',
  'South Indian Bank',
  'Standard Chartered Bank',
  'State Bank of India',
  'Sumitomo Mitsui Banking Corporation',
  'Tamilnad Mercantile Bank',
  'UCO Bank',
  'Ujjivan Small Finance Bank',
  'Union Bank',
  'United Overseas Bank',
  'Westpac',
  'Woori Bank',
  'Yes Bank',
];
